creation_rules:
  - path_regex: .*secrets?.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age1ma0krf3yzghs2zmxl8rj0fdt0gpfq8vvgk88f0807gv9dgpm7pfsdc8q3t
  - path_regex: .*secretvalue.yaml
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age1ma0krf3yzghs2zmxl8rj0fdt0gpfq8vvgk88f0807gv9dgpm7pfsdc8q3t
  - path_regex: .*.env
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age1ma0krf3yzghs2zmxl8rj0fdt0gpfq8vvgk88f0807gv9dgpm7pfsdc8q3t
